### ISSUE TITLE
Suport default units 'px'

### ISSUE THREAD

**Issue by suchangv** [07akioni/css-render#650]
Can you support omitting the default units 'px'? just like React. Thx~

```javascript
c("body", {
  margin: 4,
});
```
output
```css
body {
  margin: 4;
}
```
expect
```css
body {
  margin: '4px'
}
```
